name: dicoding_restaurant_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <=3.3.4"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #additional dependencies
  google_fonts: ^3.0.1
  http: ^0.13.5
  provider: ^6.0.4
  fluttertoast: ^8.1.1
  path: ^1.8.2
  sqflite: ^2.2.0+2
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^12.0.3
  rxdart: ^0.27.5
  android_alarm_manager_plus: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  build_runner: ^2.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/restaurants.json
