name: dicoding_restaurant_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <=3.3.4"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #additional dependencies
  google_fonts: ^3.0.1
  http: ^0.13.5
  provider: ^6.0.4
  fluttertoast: ^8.1.1
  path: ^1.8.2
  sqflite: ^2.2.0+2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/restaurants.json
